name = "mova-tool-door-v0-dev"
main = "src/index.ts"
compatibility_date = "2026-01-16"

[[d1_databases]]
binding = "TOOL_DOOR_DB" # i.e. access this D1 Database via env.TOOL_DOOR_DB
database_name = "mova-tool-door-v0-db"
database_id = "5f6917ba-ab24-4f80-9212-a0456a929b69"

[vars]
TOOL_DOOR_POLICY_PATH = "policies/tool_door/policy_profiles_v0.json"